server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lioilroot
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
