server:
  port: 8081
custom:
    username: 半圆

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: lioilroot
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:club/banyuan/mapper/*.xml
  type-aliases-package: club.banyuan.entity
  configuration:
    map-underscore-to-camel-case: true
